export {default as Header} from './Header'
export {default as TopWrapper} from './TopWrapper'
export {default as AboutWrapper} from './AboutWrapper'
export {default as SkillWrapper} from './SkillWrapper' 
export {default as WorkWrapper} from './WorkWrapper' 
export {default as ContactWrapper} from './ContactWrapper'
export {default as Footer} from './Footer' 